Recognize segwit signatures in decoded TX even if witness not present
When running `t/recreate-as-psbt extra-keys-nonsegwit` I saw this
failure:

NotImplementedError: unrecognized scriptsig in vin: {'vout': 1, 'sequence': 4294967295, 'txid': '724a53bad920fae74ff7956ca7c5bf3dcc3ae355f7f98cfa3411cd95318b69bf', 'scriptSig': {'asm': '001424a5335edd0c9715fe635ee28ffc3c35aeec8996', 'hex': '16001424a5335edd0c9715fe635ee28ffc3c35aeec8996'}}

The problem is that PSBTs with non_witness_utxo, I assume in order to
save space, do not include witness signatures, since such signatures
are not necessary for the signer to validate the TXID.

This extra-keys-nonsegwit test was the first that I tried where we had
a nonsegwit cold-storage address and whose input TXs had witness
outputs, which is why this is the first time I saw this.